### ISSUE TITLE
[UI] Search

### ISSUE THREAD

**Issue by thimy** [etalab/entreprise.data.gouv.fr#1]
You'll find here some proposals that are open for discussion. Layout, colours, typefaces, anything can be changed. :)

Once we settle on something I'll extend this to a desktop version.

## Search
![sirene - search 1](https://user-images.githubusercontent.com/1301085/28264033-6961ed00-6ae9-11e7-8821-56f37180bb0c.jpg)
![sirene - search 2](https://user-images.githubusercontent.com/1301085/28264034-6b9c8d8c-6ae9-11e7-8989-3c74bf048616.jpg)

## Results
![sirene - results 3](https://user-images.githubusercontent.com/1301085/28264036-6f7e5c28-6ae9-11e7-9c23-9b90fbd15f27.jpg)
![sirene - results 1](https://user-images.githubusercontent.com/1301085/28264038-6f980c18-6ae9-11e7-9bb8-60399f52a39d.jpg)
![sirene - results 2](https://user-images.githubusercontent.com/1301085/28264037-6f973644-6ae9-11e7-80a8-8529619d1fad.jpg)

**Comment by giglemad** [comment]
For results display i would go with option 3, i feel the contrast of this option is great for the accessibility and readability purposes. Helps drawing a clear delimitation of UI blocks and reduce cognitive overload for users.

**Comment by Zerhariel** [comment]
Same feelings than @giglemad for the result display.
For search I have a slight preference for the first, research field being after the explanation, especially since this is the V1 version.
