### ISSUE TITLE
Redesign + Rewriting result page

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/entreprise.data.gouv.fr#20]

**Comment by thimy** [comment]
![results](https://user-images.githubusercontent.com/1301085/30555664-7d1a754c-9ca8-11e7-9d06-42045e52079d.jpg)

![results2](https://user-images.githubusercontent.com/1301085/30555671-80960e66-9ca8-11e7-8955-82273382361a.jpg)

We can probably add more filters to balance the columns.
The second version doesn't have an outer shadow.
The toggle buttons in the second version is probably too strong.
We should probably be able to propose to change the number of results displayed.

Of course all of this can be mixed. :)

Any thoughts?

**Comment by giglemad** [comment]
Test in future open lab the positionment of filter component (left or right)
