### ISSUE TITLE
Codeclimate badges

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/entreprise.data.gouv.fr#308]
- Maintanibility badge should be removed since vue.js isnt supported by codeclimate
- Code coverage isn't representative of what's really under the hood, need to make it better, for example by excluding functions that should not be tested (such as vuex getters)

**Comment by brindu** [comment]
Why Vuex getters should be tested ?

**Comment by Samuelfaure** [comment]
should NOT, imho

**Comment by Samuelfaure** [comment]
If your question was why they shouldn't be tested, I think vue getters have too low a complexity to justify testing. Most of them are simple return statements, sometimes with an IF condition.

**Comment by Samuelfaure** [comment]
Change code coverage from codeclimate to vue-coverage maybe : https://medium.com/javascript-in-plain-english/add-test-coverage-to-vue-js-app-with-jest-travis-ci-and-coveralls-d10d118125c2

**Comment by Samuelfaure** [comment]
fixed in  45c3f38
