### ISSUE TITLE
Wording sur page etablissement

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/entreprise.data.gouv.fr#326]
Retour utilisateur :

Hello, une petite remarque sur le wording sur les pages entreprise.data.gouv. Sur https://entreprise.data.gouv.fr/etablissement/83371879400013, je lis :
 Cet établissement est le siège social.
et deux lignes plus loin
 Le siège social de cet établissement est : PARIS LA DEFENSE 833 718 794 00013
C'est contre intuitif.

**Comment by brindu** [comment]
Fixed in #355
