### ISSUE TITLE
Amélioration : titres des pages par défaut / pages entreprises

### ISSUE THREAD

**Issue by risseraka** [etalab/entreprise.data.gouv.fr#342]
Au chargement de entreprise.data.gouv.fr, on voit "Vue App" apparaître rapidement dans le nom de l'onglet avant que ça se mette à "Accueil | Entreprise.data.gouv.fr".
Dans le header, on a : `<title>Vue App</title>`
Ce serait propre de mettre quelque chose par défaut comme "Entreprise.data.gouv.fr".
(Par contre, je n'ai pas trouvé où le faire https://github.com/etalab/entreprise.data.gouv.fr/search?q=title)

De la même façon, le `title` d'une page établissement pourrait être complété avec le nom de l'entreprise, actuellement on a que "| Entreprise.data.gouv.fr"
Ex : https://entreprise.data.gouv.fr/etablissement/429677446

**Comment by brindu** [comment]
Fixed in #355
