### ISSUE TITLE
mauvaise adresse de contact

### ISSUE THREAD

**Issue by taniki** [etalab/entreprise.data.gouv.fr#358]
https://github.com/etalab/entreprise.data.gouv.fr/blob/a0970cd339343b59743d4c2328fafdb71e73e512/src/components/layout/AppFooter.vue#L27

Cette adresse n'est plus officiellement utilisée. On essaie de faire du triage entre support@data.gouv.fr pour toutes les questions techniques/plateforme et ouverture@data.gouv.fr pour les questions d'ouverture et de manipulation de données.

Peut être qu'il y a aussi déjà une adresse de support plus appropriée de votre côté.

**Comment by brindu** [comment]
J'ai vais mettre entreprise@data.gouv.fr qui est la boite mail du support sur entreprise.data 👍
