### ISSUE TITLE
[UI] Results

### ISSUE THREAD

**Issue by thimy** [etalab/entreprise.data.gouv.fr#7]
I tried to stick with the mobile version but I'm not exactly satisfied with this but this could help while I'm away. If you have suggestions feel free to comment!
I feel like categories should not be in the middle but should however be aligned with results on 1 and 2.
Maybe filters should be on the right?
On 3, I think that filters put in horizontal take too much space.

![desktop](https://user-images.githubusercontent.com/1301085/28615390-24e2be90-71f9-11e7-9b0a-de9b237d274e.jpg)
![desktop2](https://user-images.githubusercontent.com/1301085/28615392-27813190-71f9-11e7-939d-c2b732b4d4b6.jpg)
![desktop3](https://user-images.githubusercontent.com/1301085/28615396-29be8b06-71f9-11e7-9cdf-85a498646c39.jpg)

**Comment by Zerhariel** [comment]
As we discussed, I feel the #1 and #2 don't seem convenient for displaying a larger number of results, which I guess is going to be needed, 4 results being quite a small number. So as a personal choice I'd go with #3 for now, IMHO.
